# Explore Errors Task

# Create a NameError
# nameerrors value is not referenced before being called

def createNameError():
	return nameerrors

# Create a TypeError
# Cannot add a int and str together because they are different types

def createTypeError():
	a = 5
	b = "foo"
	return a + b



# Function Testing

# createNameError()
# createTypeError()